### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by rgarrigue** [Lowess/drone-molecule#1]
Hey

I found your work on docker hub looking for a molecule image. Since I'm willing to give a try at Drone and a molecule test is my use case, I'ld like to try your plugin.

Can you add a pipeline example in the README.md ? 

Best regards,

**Comment by Lowess** [comment]
Hey @rgarrigue,

Thanks for your interest in this drone plugin. I will address this really soon !

**Comment by Lowess** [comment]
Addressed in https://github.com/Lowess/drone-molecule/pull/2

**Comment by Lowess** [comment]
@rgarrigue you might also want to check out this project, you might find it useful: https://github.com/Lowess/gumsible-oh-my-zsh-plugin
